### ISSUE TITLE
The following configuration fields are not understood: {'database'}

### ISSUE THREAD

**Issue by theodotos** [matrix-org/sygnal#109]
I am running sygnal following the instructions in the README: `python -m sygnal.sygnal`

I am using sqlite3 exactly like in the sample configuration:

```
database:
  name: sqlite3
  args:
    dbfile: sygnal.db
```

But I get this:

```
The following configuration fields are not understood: {'database'}
```

Any idea?
