### ISSUE TITLE
No log output from V1NotifyHandler._handle_request()

### ISSUE THREAD

**Issue by awesome-manuel** [matrix-org/sygnal#161]
I cannot get any log output from logging calls inside  V1NotifyHandler._handle_request().

**To Reproduce**
1. Install `sygnal` using docker
2. Configure output logging with INFO level
3. Send an invalid notification request:
 `curl -X POST -H "Content-Type: application/json" -d '{}' https://<server>/_matrix/push/v1/notify`

**Expected behavior**
Log should read:
```
2020-12-07 16:16:32,270 [1] WARN  Invalid notification: expecting object in 'notification' key
2020-12-07 16:16:32,270 [1] INFO  sygnal.access Handled request: "-" - - [07/Dec/2020:16:16:32 +0000] "POST /_matrix/push/v1/notify HTTP/1.1" 400 26 "-" "curl/7.68.0"
```

but the first line is missing.

**Comment by anoadragon453** [comment]
Looks like `V1NotifyHandler` makes use of a specialised class named `NotificationLoggerAdapter`:

https://github.com/matrix-org/sygnal/blob/a981860f4f660c9509f2851a264de7f2b52a3b61/sygnal/http.py#L133

It's possible that something is wrong with this adapter, or that the provided log config is excluding it.

@awesome-manuel could you post the `log` section of your config so I can have a look please?

**Comment by awesome-manuel** [comment]
```yaml
log:
  setup:
    version: 1
    formatters:
      normal:
        format: "%(asctime)s [%(process)d] %(levelname)-5s %(name)s %(message)s"
    handlers:
      stdout:
        class: "logging.StreamHandler"
        formatter: "normal"
        stream: "ext://sys.stdout"
        level: "DEBUG"
    root:
      handlers: ["stdout"]
      level: "DEBUG"
```
