### ISSUE TITLE
Some messages just don't arrive

### ISSUE THREAD

**Issue by chagai95** [matrix-org/sygnal#169]
**Describe the bug**
Some messages just don't arrive, nothing more to say...

**To Reproduce**
very difficult

**Expected behavior**
All messages should arrive

**Smartphone (please complete the following information):**
 - Device: Xiaomi 8
 - OS: MIUI 12
 - Version: debug branch

**Additional context**
Most messages do arrive

**Comment by clokep** [comment]
Can you provide more information about the version of Sygnal that's being run? Are there any errors in the Sygnal log?

**Comment by chagai95** [comment]
I built a docker image from this repo 3 weeks ago and there are no errors in the logs...

`docker build -t as/sygnal -f docker/Dockerfile .`
`as/sygnal                                                      latest              6365ad6e0461   3 weeks ago     186MB`

I think I correctly set it to log DEBUG:


```
log:
  # Specify a Python logging 'dictConfig', as described at:
  #   https://docs.python.org/3.7/library/logging.config.html#logging.config.dictConfig
  #
  setup:
    version: 1
    formatters:
      normal:
        format: "%(asctime)s [%(process)d] %(levelname)-5s %(name)s %(message)s"
    handlers:
      # This handler prints to Standard Error
      #
      stderr:
        class: "logging.StreamHandler"
        formatter: "normal"
        stream: "ext://sys.stderr"

      # This handler prints to Standard Output.
      #
      stdout:
        class: "logging.StreamHandler"
        formatter: "normal"
        stream: "ext://sys.stdout"

      # This handler demonstrates logging to a text file on the filesystem.
      # You can use logrotate(8) to perform log rotation.
      #
      file:
        class: "logging.handlers.WatchedFileHandler"
        formatter: "normal"
        filename: "./sygnal.log"
    loggers:
      # sygnal.access contains the access logging lines.
      # Comment out this section if you don't want to give access logging
      # any special treatment.
      #
      sygnal.access:
        propagate: false
        handlers: ["stdout"]
        level: "DEBUG"

      # sygnal contains log lines from Sygnal itself.
      # You can comment out this section to fall back to the root logger.
      #
      sygnal:
        propagate: false
        handlers: ["stderr", "file"]

    root:
      # Specify the handler(s) to send log messages to.
      handlers: ["stderr"]
      level: "DEBUG"

    disable_existing_loggers: false



```
