### ISSUE TITLE
ios notification -fluffyChat

### ISSUE THREAD

**Issue by Sphinix1** [matrix-org/sygnal#324]
hi , 
i am using sygnal (self-hosted) with fluffychat. I dont seem to have notification pop-up unless fluffychat(ios) is running on the foreground.
i have tried all the suggestions i could find . what am i missing . 
here is my sygnal.yaml

```
apps:



    im.cvccc.cvcvc:
        keyfile: /data/AuthKey_zzzzzzzzz.p8
        team_id: xxcccccc
        key_id: cvvvvvvv
        topic: im.cvccc.cvcvc
        type: apns
                fcm_options:
                    content_available: true
                    priority: high
                    badge : 9
                    sound : bingbong.aiff
                    mutable_content: 1
http:
    bind_addresses:
    - '::'
    port: 6000
log:
    access:
        x_forwarded_for: true
    setup:
        disable_existing_loggers: false
        formatters:
            normal:
                format: '%(asctime)s [%(process)d] %(levelname)-5s %(name)s %(message)s'
        handlers:
            stderr:
                class: logging.StreamHandler
                formatter: normal
                stream: ext://sys.stderr
            stdout:
                class: logging.StreamHandler
                formatter: normal
                stream: ext://sys.stdout
        loggers:
            sygnal:
                handlers:
                - stderr
                propagate: false
            sygnal.access:
                handlers:
                - stdout
                level: INFO
                propagate: false
        root:
            handlers:
            - stderr
            level: INFO
        version: 1
metrics:
    opentracing:
        enabled: false
        implementation: jaeger
        jaeger:
            logging: true
            sampler:
                param: 1
                type: const
        service_name: sygnal
    prometheus:
        address: 0.0.0.0
        enabled: false
        port: 8000
    sentry:
        enabled: false
```
