### ISSUE TITLE
FCM push for iOS issue

### ISSUE THREAD

**Issue by tzigdon** [matrix-org/sygnal#337]
Hey,

I'm trying to implement iOS push via FCM in Sygnal.

My Sygnal.yaml file looks like this:

```yaml
  <bundle id>:
    type: gcm
    api_key: <api key>
    max_connections: 20
    inflight_request_limit: 512
    fcm_options:
      content_available: true
      mutable_content: true
```
      
I am getting this error:

```
 sygnal.gcmpushkin [604c950e-dfa4-4c44-8fb5-314505c91917] Reg ID '<id>' has temporarily failed with code 'InvalidParameters: "aps" key is not permitted'
```
 
 any Idea what is the issue? as far as I understand, aps key is android only key.

thanks in advance for any help
