### ISSUE TITLE
Synapse not able to access Sygnal in docker compose

### ISSUE THREAD

**Issue by theobouwman** [matrix-org/sygnal#399]
I want to use Synapse with Sygnal for push notifications.

When I register a pusher, and a new push notification is sent I get this error stating that the Sygnal instance is blocked?:
```
synapse-1                | 2024-10-29 22:00:12,087 - synapse.push.httppusher - 236 - INFO - httppush.process-17 - Processing 2 unprocessed push actions for @deff67df-8c84-4782-87cb-5d2ce6b2c59f:test.my.com/com.my.app/xxxxxxxx starting at stream_ordering 589
synapse-1                | 2024-10-29 22:00:12,101 - synapse.http.client - 202 - INFO - sentinel - Blocked 172.18.0.4 from DNS resolution to sygnal
synapse-1                | 2024-10-29 22:00:12,101 - synapse.http.client - 437 - INFO - httppush.process-17 - Error sending request to  POST http://sygnal:5000/_matrix/push/v1/notify: DNSLookupError no results for hostname lookup: sygnal
synapse-1                | 2024-10-29 22:00:12,101 - synapse.push.httppusher - 416 - WARNING - httppush.process-17 - Failed to push data to @deff67df-8c84-4782-87cb-5d2ce6b2c59f:test.my.com/com.my.app/xxxxxxxxx: <class 'twisted.internet.error.DNSLookupError'> DNS lookup failed: no results for hostname lookup: sygnal.
synapse-1                | 2024-10-29 22:00:12,101 - synapse.push.httppusher - 315 - INFO - httppush.process-17 - Push failed: delaying for 512s
```

**What could be the issue here?**

_**Here my config:**_
docker-compose:
```
synapse:
    image: docker.io/matrixdotorg/synapse:latest
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - ./synapse/files:/data
      - ./synapse/synapse-modules/synapse_user_restrictions:/synapse_user_restrictions
    depends_on:
      - synapse-db
    networks:
      - default
    ports:
      - 8008:8008

  synapse-db:
    image: docker.io/postgres:12-alpine
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=synapse
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./synapse/schemas:/var/lib/postgresql/data
    networks:
      - default
    ports:
      - 5433:5432

  sygnal:
    image: matrixdotorg/sygnal:latest
    restart: unless-stopped
    environment:
      - SYGNAL_CONF=/data/sygnal.yaml
    volumes:
      - ./synapse/sygnal:/data
    ports:
      - 5000:5000
    networks:
      - default
```

Code to setPusher:
```ts
client.setPusher({
                "app_display_name": "app",
                "app_id": "com.my.app",
                "data": {
                    url: "http://sygnal:5000/_matrix/push/v1/notify"
                },
                "device_display_name": `my device`,
                "kind": "http",
                "lang": 'en',
                "pushkey": pushToken,
                "enabled": true,
            })
```

From the Synapse container I am able to access the Sygnal server with curl:
![Screenshot 2024-10-29 at 22 57 44](https://github.com/user-attachments/assets/8aaecdea-e58c-4db2-a48a-497ce89fa546)
