### ISSUE TITLE
Example config is missing "platform"

### ISSUE THREAD

**Issue by awesome-manuel** [matrix-org/sygnal#80]
The key "platform" seems to be required for `apns`.
Somehow I don't even get an error if it is missing, sygnal is just not starting up.

**Comment by reivilibre** [comment]
You're right that it could do with documenting (oups...)

BUT it won't prevent startup (both code and experience agree here...).

Could you share a bit more about your config (removing secrets), and your log?

**Comment by awesome-manuel** [comment]
```yaml
log:
  setup:
    version: 1
    formatters:
      normal:
        format: "%(asctime)s [%(process)d] %(levelname)-5s %(name)s %(message)s"
    handlers:
      stdout:
        class: "logging.StreamHandler"
        formatter: "normal"
        stream: "ext://sys.stdout"
    root:
      handlers: ["stdout"]
      level: "INFO"
  access:
    x_forwarded_for: true

http:
  bind_addresses: ['0.0.0.0']
  port: 5000

apps:
  <id>:
    type: apns
    platform: prod
    certfile: mycert.pem
```
