### ISSUE TITLE
VOIP: config for ios

### ISSUE THREAD

**Issue by Udit-DS** [matrix-org/sygnal#82]
I have following config in `sygnal.yaml` file for ios voip notifications

```
com.app.voip:
    type: apns
    certfile: certfile.pem
    platform: sandbox
    event_handlers:
      'm.call.invite': voip
```

but every time the `rejected` response and sometimes even BadDeviceToken(in logs) response

is there something I am missing?
